version: 2
project_name: jack

builds:
  - id: jack
    main: ./cmd/jack
    binary: jack
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

changelog:
  use: github
  sort: asc
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
    - title: "Performance"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: zoobzio
    name: jack
  draft: false
  prerelease: auto
  mode: append
